# Detect changes to a helm chart by comparing with this remote/branch.
remote: origin
target-branch: master

# What to check.
validate-chart-schema: true
validate-yaml: true
validate-schema-chart: true
validate-maintainers: false
check-version-increment: true

# Adds remote chart repositories to be used for the tests.
chart-repos:
  - stable=https://kubernetes-charts.storage.googleapis.com/
  - falcosecurity=https://falcosecurity.github.io/charts

# Consider helm charts in all directories.
chart-dirs:
  - charts

helm-extra-args: --timeout 800s

#excluded-charts:
#  - landing
