# permissions for end users to edit admins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: admin-controller
    app.kubernetes.io/managed-by: kustomize
  name: admin-editor-role
rules:
- apiGroups:
  - emprovise.emprovise.com
  resources:
  - admins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - emprovise.emprovise.com
  resources:
  - admins/status
  verbs:
  - get
